namespace: production

api:
  image:
    repository: 388465176512.dkr.ecr.us-east-1.amazonaws.com/wrench/api
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1
  containerPort: 8080
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 6
    targetCPUUtilizationPercentage: 50

gateway:
  name: bgt3-gw
  namespace: gateway

httpRoute:
  hostname: api.bgt3.com.br

database:
  host: prod-db.bgt3.com.br
  port: 5432
  user: wrench_app
  password: trocar-no-deploy
  name: wrench_auto_repair

jwt:
  issuer: Wrench Auto Repair
  audience: Wrench Auto Repair
  expirationMinutes: 30
  signingKey: ''

application:
  environment: Production
  admin:
    email: admin@wrench.com.br
    password: ''
  no_reply:
    email: ''
  credentials:
    aws:
      region: us-east-1

serviceAccount:
  create: true
  name: wrench-api-sa
  roleArn: ''

newRelic:
  otlpEndpoint: https://otlp.nr-data.net:4318
  otlpProtocol: http/protobuf
  licenseKey: ''
