{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  {{- with .Values.serviceAccount.roleArn }}
  annotations:
    # IRSA: liga esta SA a role IAM. O EKS injeta AWS_ROLE_ARN +
    # AWS_WEB_IDENTITY_TOKEN_FILE nos pods que a usam.
    eks.amazonaws.com/role-arn: {{ . | quote }}
  {{- end }}
{{- end }}
